config/routes.rb
Rails.application.routes.draw do
  get  'users/setIdentity'

  resources :donation_lists
  resources :special_projects
  resources :downloads


	#get  'trades/donate'
	#post 'trades/post_back'
	#post 'trades/result'

  scope "(:locale)", locale: /en|zh-TW/ do
    resources :sign_reports
    resources :donations
    resources :projects
    resources :stories
    resources :links
    resources :downloaded
    as :user do
        patch '/user/confirmation' => 'users/confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "users/confirmations", :passwords => 'users/passwords' } # be careful of the order with resources users
    resources :users, only: [:index, :show, :destroy]

    post 'projects/checkLogin'
    post 'projects/delete_stage'
    post 'projects/ajax_update'

    get  'main/post_back'
    post 'main/result'
    post 'main/post_back'
    post 'main/donation'


    get  'donation', to: 'main#donation'

    get  'main/about'
    get  'main/boardMembers'
    get  'main/meetings'
    get  'main/contactUs'
    get  'main/otherLinks'
    get  'main/news'
    get  'main/donation'
    get  'main/downloaded'
    get  'main/downloadManual'
    get  'main/downloadBoardLists'
    get  'main/special'
    root 'main#about'

  end


end

app/models/download.rb
class ActiveRecord::Base
  def self.has_translation(*attributes)    
    attributes.each do |attribute|
      define_method "#{attribute}" do
        if I18n.locale == I18n.default_locale
          self.read_attribute(attribute)
        else
          self.send "#{attribute}_#{I18n.locale}"
        end
      end
    end
  end
end
class Download < ActiveRecord::Base
  has_attached_file :file_at,
      :url  => "/assets/file_ats/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :file_at
  validates :title, :title_en, presence: true
  has_translation :title  
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_download, only: [:show, :edit, :update, :destroy]

  # GET /downloads
  # GET /downloads.json
  def index
    @downloads = Download.all
  end

  # GET /downloads/1
  # GET /downloads/1.json
  def show
  end

  # GET /downloads/new
  def new
    @download = Download.new
  end

  # GET /downloads/1/edit
  def edit
  end

  # POST /downloads
  # POST /downloads.json
  def create
    @download = Download.new(download_params)
    @download.save!
    flash[:notice] = '成功新增下載'
    redirect_to action: :index
    rescue ActiveRecord::RecordInvalid
    render :action=>:edit
  end

  # PATCH/PUT /downloads/1
  # PATCH/PUT /downloads/1.json
  def update
    if params[:download_file_delete] == 'true' #delete sign_report attachments
      @download.file_at = nil
    end
    if @download.update(download_params)
      flash[:notice] = '成功更新下載'
      redirect_to action: "index"
    else
      render :edit
    end
  end

  # DELETE /downloads/1
  # DELETE /downloads/1.json
  def destroy
    @download.destroy
    redirect_to downloads_url, notice: '成功刪除下載' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_download
      @download = Download.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def download_params
      params.require(:download).permit(:title, :title_en, :file_at)
    end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/_form.html.erb
<%= form_for(@download, html: { multipart: true }) do |f| %>
<div class="container" style="margin-top: 10mm">
  <% if @download.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @download.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag(:download_file_delete, false) %>
  <div class="form-group row">
    <label class="col-sm-offset-2 col-sm-2 control-label">名稱*</label>
    <div class="col-sm-4"><%= f.text_field :title, class: "form-control", placeholder: '名稱' %></div>
  </div>
  <div class="form-group row">
    <label class="col-sm-offset-2 col-sm-2 control-label">英文名稱*</label>
    <div class="col-sm-4"><%= f.text_field :title_en, class: "form-control", placeholder: '英文名稱' %></div>
  </div>  
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">附件</label>
  	<div class="col-sm-4">
  		<%= file_field_tag "download[file_at]", type: :file%>
  	</div>
  </div>
  <div class="form-group row">
		<div class="col-sm-8">
			<%= f.submit '儲存',  class: "btn btn-info save-btn pull-right"  %>
		</div>
  </div>
</div>
<% end %>
<script>
$(document).on('ready', function() {
	//download attachment file upload
     $("#download_file_at").fileinput({
     	initialPreview: [
		    <% if !@download.file_at_file_name.blank? %>
		    "<div class='file-preview-other'>" +
    	    "<h2><i class='glyphicon glyphicon-file'></i></h2>" +
            '<%= @download.file_at_file_name%>' + "</div>"
			<% end %>
		             ],
		showUpload: false,
        browseClass: "btn btn-success",
        browseLabel: "Browse",
        browseIcon: "<i class=\"glyphicon glyphicon-folder-open\"></i> ",
        removeClass: "btn btn-danger",
        removeLabel: "Delete",
        removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
    });
    $('#download_file_at').on('fileloaded', function(event, file, previewId, index, reader) {
        $('#download_file_delete').val(true);
    });
    $('#download_file_at').on('fileclear', function(event) {
    	$('#download_file_delete').val(true);
    });
});
</script>

app/views/downloads/_sub_download_table.html.erb
	<div class="col-md-4">
	  <table class="table backend_index_table">
	  	<tbody>
	      <tr>
	        <td colspan="2"><%= download.title %></td>
	      </tr>
	      <tr style="text-align: center;">
	      	<td colspan="2">
	      		<% unless download.file_at_file_name.blank? %><%= link_to download.file_at_file_name, download.file_at.url(:original, false) %><% end %>
	      	</td>
	      </tr>
	      <tr style="text-align: center;">
		    <td colspan="2"><%= link_to "編輯", edit_download_path(download), data: { no_turbolink: true }, class: 'edit-btn', style: "margin-right:24px;" %><%= link_to '刪除', download, method: :delete, data: { confirm: 'Are you sure?' } , class: 'delete-btn', style: ""%></td>
	      </tr>
	    </tbody>
	  </table>
	</div>

app/views/downloads/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">	
			<h3 style="letter-spacing: 2px;">文件下載</h3>
			<%= link_to "新增", new_download_path, class: 'add-btn pull-right' %>
		</div>		
	</div>
</div>
<div class="container">
	<div class="row">
	<% @downloads.each do |download| %>
		<%= render "sub_download_table", download: download %>
	<% end %>
	</div>
</div>

app/views/downloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @download.title %>
</p>

<%= link_to 'Edit', edit_download_path(@download) %> |
<%= link_to 'Back', downloads_path %>