config/routes.rb
Rails.application.routes.draw do
  get  'users/setIdentity'

  resources :donation_lists
  resources :special_projects
  resources :downloads


	#get  'trades/donate'
	#post 'trades/post_back'
	#post 'trades/result'

  scope "(:locale)", locale: /en|zh-TW/ do
    resources :sign_reports
    resources :donations
    resources :projects
    resources :stories
    resources :links
    resources :downloaded
    as :user do
        patch '/user/confirmation' => 'users/confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "users/confirmations", :passwords => 'users/passwords' } # be careful of the order with resources users
    resources :users, only: [:index, :show, :destroy]

    post 'projects/checkLogin'
    post 'projects/delete_stage'
    post 'projects/ajax_update'

    get  'main/post_back'
    post 'main/result'
    post 'main/post_back'
    post 'main/donation'


    get  'donation', to: 'main#donation'

    get  'main/about'
    get  'main/boardMembers'
    get  'main/meetings'
    get  'main/contactUs'
    get  'main/otherLinks'
    get  'main/news'
    get  'main/donation'
    get  'main/downloaded'
    get  'main/downloadManual'
    get  'main/downloadBoardLists'
    get  'main/special'
    root 'main#about'

  end


end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :project
  
  validates :amount, :donate_way, :donate_date, :project_id, presence: true
  validates :order_num, uniqueness: true, on: :update
  validates :order_num, presence: true, on: :update
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @project_name = Project.find(@donation.project_id).name
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params) 
    @donation.save!
    @donation.order_num = generate_order_num()    
    @donation.save!  
    redirect_to @donation, notice: '成功新增捐款' 
    rescue ActiveRecord::RecordInvalid
    render :edit
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    if @donation.update(donation_params)
      redirect_to @donation, notice: '成功更新捐款' 
    else
      render :edit 
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    redirect_to donations_url, notice: '成功刪除捐款' 
  end

  private
    def generate_order_num
      order_no = "NO"; 
      order_no  << Date.today.to_s.gsub(/[^0-9]/, '')
      order_no << "_"+@donation.id.to_s
      return order_no
    end
      
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:name, :amount, :donate_way, :donate_date, :donate, :project_id, :receipt_title, :receipt_address, :phone, :email, :description, :order_num)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
  def donateWayOptions
    [['電匯', GLOBAL_VAR['donate_transfer']], 
     ['線上刷卡', GLOBAL_VAR['donate_credit']], 
     ['其他', GLOBAL_VAR['donate_others']]]
  end  
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
	<div class="container" style="margin-top: 10mm">
	   <% if @donation.errors.any? %>
	    <div id="error_explanation">
	      <ul>
	      <% @donation.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	  </div>
	  <% end %>
	  <%= f.hidden_field :donate, value: true %>
	  <%if @donation.persisted?%>
	  <div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">編號</label>
	  		<div class="col-sm-3">
	  			<%= f.text_field :order_num, class: "form-control", placeholder: "編號" %>
	    	</div>
	  </div>	  
	  <%end%>
	  <div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">聯絡人</label>
	  		<div class="col-sm-3">
	  			<%= f.text_field :name, class: "form-control", placeholder: "聯絡人" %>
	    	</div>
	  </div>
	  <div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">金額*</label>
	  		<div class="col-sm-3">
	  			<%= f.number_field :amount, class: "form-control", placeholder: "金額" %>
	    	</div>
	  </div>
	  <div class="form-group row">
			<label class="col-sm-offset-3 col-sm-2 control-label">捐款方式*</label>
			<div class="col-sm-3">
				<%= f.select :donate_way , options_for_select([["電匯", 0], ["線上刷卡", 1], ["其它", 2]], @donation.donate_way) , {prompt: '選擇捐款方式'}, class: "form-control" %>		
	  		</div>
	  </div>
	  <div class="form-group row">
			<label class="col-sm-offset-3 col-sm-2 control-label">計畫*</label>
			<div class="col-sm-3">
	  			<%= f.select :project_id , options_from_collection_for_select(Project.all, 'id', 'name', @donation.project_id),{prompt: '選擇計畫'} , class: "form-control"%>
	  		</div>
	  </div>
	  <div class="form-group row">
			<label class="col-sm-offset-3 col-sm-2 control-label">日期*</label>
			<div class="col-sm-3">
				<%= f.text_field :donate_date, class: "form-control", id: 'datetimepicker_donate_date', placeholder: "捐款日期" %>	
			</div>
		    <script type="text/javascript">
		            $(function () {
		                $('#datetimepicker_donate_date').datetimepicker({
							format : 'YYYY/MM/DD'		                
		                });
		            });
		    </script>	
		</div>
	<div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">抬頭</label>
	  		<div class="col-sm-3">
	  			<%= f.text_field :receipt_title, class: "form-control", placeholder: "抬頭" %>
	    	</div>
	</div>
	<div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">地址</label>
	  		<div class="col-sm-3">
	  			<%= f.text_field :receipt_address, class: "form-control", placeholder: "地址" %>
	    	</div>
	</div>
	<div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">說明</label>
	  		<div class="col-sm-3">
	  			<%= f.text_area :description, class: "form-control", placeholder: "說明" %>
	    	</div>
	</div>	
	<div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">電話</label>
	  		<div class="col-sm-3">
	  			<%= f.phone_field :phone, class: "form-control", placeholder: "電話" %>
	    	</div>
	</div>
	<div class="form-group row">
	  	<label class="col-sm-offset-3 col-sm-2 control-label">Email</label>
	  		<div class="col-sm-3">
	  			<%= f.email_field :email, class: "form-control", placeholder: "Email" %>
	    	</div>
	</div>
		<div class="form-group row">
			<div class="col-sm-offset-9 col-sm-2 pull-right-lg">
				<%= f.submit '儲存',  class: "btn btn-info save-btn"  %>
			</div>
		</div>
	</div>
<% end %>

app/views/donations/_sub_donation_panel.html.erb
<%= link_to donation_path(donation) do %>
	<div class="col-md-4">
	  <table class="table donation_backend_table">
	  	<tbody>
	      <tr style="border-left: solid black 5px;">
	        <td><%= Project.find(donation.project_id).name%></td>
	      </tr>
	      <tr>
	        <th>連絡人: </th>
	        <td><%= donation.name %></td>
	      </tr>
	      <tr>
	        <th>金額: </th>
	        <td><%= donation.amount %></td>
	      </tr>
	      <tr>
	        <th>方式: </th>
	        <td><%= Hash[donateWayOptions].rassoc(donation.donate_way).first %></td>
	      </tr>
	      <tr>
	      	<% if donation.donate %>
	      		<th>已捐款</th>
	      	<% else %>
	      		<th>尚未捐款</th>
	      	<% end %>
	      </tr>
	      <tr>
	    </tbody>
	  </table>
	</div>
<% end %>

app/views/donations/_sub_donation_table.html.erb
<%= link_to donation_path(donation) do %>
	<div class="col-md-4">
	  <table class="table backend_index_table">
	  	<tbody>
	      <tr>
	        <td colspan="2"><%= Project.find(donation.project_id).name%></td>
	      </tr>
	      <tr>
	        <th>編號 </th>
	        <td><%= donation.order_num %></td>
	      </tr>	      
	      <tr>
	        <th>抬頭 </th>
	        <td><%= donation.receipt_title %></td>
	      </tr>
	      <tr>
	        <th>金額 </th>
	        <td><%= number_with_delimiter donation.amount || 0 %> 元</td>
	      </tr>
	      <tr>
	        <th>捐款方式 </th>
	        <td><%= Hash[donateWayOptions].rassoc(donation.donate_way).first %></td>
	      </tr>
	      <tr>
	      	<% if donation.donate %>
	      		<th>已捐款</th>
	      	<% else %>
	      		<th style="color: #b30000">尚未捐款</th>
	      	<% end %>
	      </tr>
	      <tr>
	    </tbody>
	  </table>
	</div>
<% end %>

app/views/donations/edit.html.erb
<%= render 'form' %>

app/views/donations/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">	
			<h3 style="letter-spacing: 2px;">捐款</h3>	
			<%= link_to "新增", new_donation_path, class: 'add-btn pull-right' %>				
		</div>		
	</div>
</div>
<div class="container">
	<div class="row">
		<% @donations.order('id desc').each do |donation| %>
			<%= render "sub_donation_table", donation: donation %>
		<% end %>
    </div>	
</div>

app/views/donations/new.html.erb
<%= render 'form' %>

app/views/donations/show.html.erb
<div class="container" style="margin-bottom: 20px;">
  <div class="row">
	<h3 class="col-sm-5">捐款明細</h3>
  </div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= link_to '刪除', @donation, method: :delete, data: { confirm: 'Are you sure?' } , class: 'delete-btn pull-right'%>
			<%= link_to "編輯", edit_donation_path(@donation), class: 'edit-btn pull-right', style: "margin-right: 20px" %>
		</div>
	</div>
</div>
<div class="container">
	  <div class="row">

	<table class="table donation_show_table">
	    <tbody style="border-left: solid 13px #194180 !important;">
	      <tr>
	        <td colspan="8" class="dt-content" style="font-weight: 900!important; background: #e3e3e3; font-size: 16px;"><%= @project_name %></td>
	      </tr>
	      <tr>
	      	<td class="dt-title">聯絡人</td>
	        <td colspan="3" class="dt-content"><%= @donation.name %></td>
	        <td class="dt-title">編號</td>
	        <td colspan="3" class="dt-content"><%= @donation.order_num %></td>
	      </tr>
	      <tr>
	        <td class="dt-title">金額</td>
	        <td colspan="1" class="dt-content"><%= number_with_delimiter @donation.amount || 0 %>元整</td>
	        <td colspan="1" class="dt-title">捐款方式</td>
	        <td colspan="1" class="dt-content"><%= Hash[donateWayOptions].rassoc(@donation.donate_way).first %></td>
	      	<td colspan="1" class="dt-title">日期</td>
	      	<td colspan="2" class="dt-content"><%= @donation.donate_date.strftime("%Y-%m-%d") %></td>
	      </tr>
	      <tr>
	        <td class="dt-title">抬頭</td>
	        <td colspan="1" class="dt-content"><%= @donation.receipt_title %></td>
	        <td colspan="1" class="dt-title">電話</td>
	        <td colspan="1" class="dt-content"><%= @donation.phone %></td>
	        <td colspan="1" class="dt-title">Email</td>
	        <td colspan="2" class="dt-content"><%= @donation.email %></td>
	      </tr>
	      <tr>
	        <td class="dt-title">地址</td>
	        <td colspan="7" class="dt-content"><%= @donation.receipt_address %></td>
	      </tr>
	      <tr>
	        <td class="dt-title">說明</td>
	        <td colspan="7" class="dt-content"><%= @donation.description %></td>
	      </tr>
	      <tr>
	        <td colspan="8" class="dt-content" style="padding:4px 16px!important;">
	        	<%= link_to "列印收據(說明:自訂)", "#", onclick:"printData('"+ @donation.description.to_s+"');", class: 'btn btn-info print-btn pull-right'  %>
	        	<%= link_to "列印收據(說明:計畫名稱)", "#", onclick:"printData('"+ @project_name +"');", class: 'btn btn-info print-btn pull-right', style: 'margin-right: 5px;' %>
	        </td>
	      </tr>
	    </tbody>
	</table>
	</div>
</div>
<div id="printTable" style="display: none;">
<style>
.logo_text{
	height: 42px;
}
.print-table {
	border-collapse: collapse;
	font-size: 20px;
    width: 206mm;
    border: 1px solid;
    font-size: 14px;
}
.print-table th {
    height: 10mm;
    width: 25mm;
    border: 2px solid;
}
.print-table td {
    height: 10mm;
    width: 35mm;
    border: 2px solid;
    text-align: center;
}
@page{ size:auto; margin-top:5mm; margin-bottom:5mm;}
</style>
<div style="text-align: right; font-size: 13px; padding-top: 7.5mm">捐款收據編號: <%= @donation.order_num %></div>
<table class="print-table">
<tbody>
	<tr>
		<td colspan="8"><%=image_tag 'logo_text.png', class: 'logo_text'%><span style="margin-left: 8px;">捐款收據</span>
			<div style="font-size: 80%">法人登記簿第11冊第17頁第295號 國稅局統一編號:98285331<br>
				 所得稅減免字號: 北區國稅竹市資第8300115086號<br>
				 新竹市大學路1001號 負責人: 林嘉勲<br>
				 郵政劃撥儲金帳戶: 18372451 號 財團法人交大思源基金會
			</div>
			<div style="float: right; margin-right: 15px;">中華民國<span style="margin-left: 3px;"><%= @donation.donate_date.year-1911 %> 年</span><span style="margin-left: 3px;"><%= @donation.donate_date.month %> 月</span><span style="margin-left: 3px;"><%= @donation.donate_date.day %> 日</span></div>
		</td>
	</tr>
	<tr >
		<th>茲收到</th>
		<td colspan="7" style="text-align: left;"><%= @donation.receipt_title %></td>
	</tr>
	<tr>
		<th>金額</th>
		<td colspan="7" style="text-align: left;" class="print_amount"></td>
	</tr>
		<th>說明</th>
		<td colspan="7" style="text-align: left;" class="description_print"></td>
	<tr>
		<td>執行長或授權代理人</td>
		<td></td>
		<td>會計</td>
		<td></td>
		<td>出納</td>
		<td></td>
		<td>經手人</td>
		<td></td>
	</tr>
</tbody>
</table>
<div style="font-size: 13px; height: 60px;">
	<div style="float: left">承蒙慷慨贊助，敬致謝枕</div>
	<div style="float: right; color: red;">收執聯</div>
</div>
<div style="text-align: right; font-size: 13px; border-top: 2px dashed #000000; padding-top: 14.5mm">捐款收據編號: <%= @donation.order_num %></div>
<table class="print-table">
<tbody>
	<tr>
		<td colspan="8"><%=image_tag 'logo_text.png', class: 'logo_text' %><span style="margin-left: 8px;">捐款收據</span>
			<div style="font-size: 80%">法人登記簿第11冊第17頁第295號 國稅局統一編號:98285331<br>
				 所得稅減免字號: 北區國稅竹市資第8300115086號<br>
				 新竹市大學路1001號 負責人: 林嘉勲<br>
				 郵政劃撥儲金帳戶: 18372451 號 財團法人交大思源基金會
			</div>
			<div style="float: right; margin-right: 15px;">中華民國<span style="margin-left: 3px;"><%= @donation.donate_date.year-1911 %> 年</span><span style="margin-left: 3px;"><%= @donation.donate_date.month %> 月</span><span style="margin-left: 3px;"><%= @donation.donate_date.day %> 日</span></div>
		</td>
	</tr>
	<tr >
		<th>茲收到</th>
		<td colspan="7" style="text-align: left;"><%= @donation.receipt_title %></td>
	</tr>
	<tr>
		<th>金額</th>
		<td colspan="7" style="text-align: left;" class="print_amount"></td>
	</tr>
		<th>說明</th>
		<td colspan="7" style="text-align: left;" class="description_print"></td>
	<tr>
		<td>執行長或授權代理人</td>
		<td></td>
		<td>會計</td>
		<td></td>
		<td>出納</td>
		<td></td>
		<td>經手人</td>
		<td></td>
	</tr>
</tbody>
</table>
<div style="font-size: 13px; height: 60px">
	<div style="float: left">承蒙慷慨贊助，敬致謝枕</div>
	<div style="float: right; color: red;">出納聯</div>
</div>
<div style="text-align: right; font-size: 13px; border-top: 2px dashed #000000; padding-top: 14.5mm">捐款收據編號: <%= @donation.order_num %></div>
<table class="print-table">
<tbody>
	<tr>
		<td colspan="8"><%=image_tag 'logo_text.png', class: 'logo_text' %><span style="margin-left: 8px;">捐款收據</span>
			<div style="font-size: 80%">法人登記簿第11冊第17頁第295號 國稅局統一編號:98285331<br>
				 所得稅減免字號: 北區國稅竹市資第8300115086號<br>
				 新竹市大學路1001號 負責人: 林嘉勲<br>
				 郵政劃撥儲金帳戶: 18372451 號 財團法人交大思源基金會
			</div>
			<div style="float: right; margin-right: 15px;">中華民國<span style="margin-left: 3px;"><%= @donation.donate_date.year-1911 %> 年</span><span style="margin-left: 3px;"><%= @donation.donate_date.month %> 月</span><span style="margin-left: 3px;"><%= @donation.donate_date.day %> 日</span></div>
		</td>
	</tr>
	<tr >
		<th>茲收到</th>
		<td colspan="7" style="text-align: left;"><%= @donation.receipt_title %></td>
	</tr>
	<tr>
		<th>金額</th>
		<td colspan="7" style="text-align: left;" class="print_amount"></td>
	</tr>
		<th>說明</th>
		<td colspan="7" style="text-align: left;" class="description_print"></td>
	<tr>
		<td>執行長或授權代理人</td>
		<td></td>
		<td>會計</td>
		<td></td>
		<td>出納</td>
		<td></td>
		<td>經手人</td>
		<td></td>
	</tr>
</tbody>
</table>
<div style="font-size: 13px;">
	<div style="float: left">承蒙慷慨贊助，敬致謝枕</div>
	<div style="float: right; color: red;">會計聯</div>
</div>




</div>
<script>
$(document).on('ready', function() {
   var digit_uppercase = function (n) {
    var digit = [
        '零' , '壹' , '貳' , '叁' , '肆' ,
        '伍' , '陸' , '柒' , '捌' , '玖'
    ];
    var unit = [ '' , '拾' , '佰' , '仟' ];
    var group = [ '元' , '萬' , '億' ];

    var s = '' ;
    for ( var i = 0; i < group.length && n > 0; i++) {
        var p = '' ;
        for ( var j = 0; j < unit.length && n > 0; j++) {
            p = digit[n % 10] + unit[j] + p;
            n = Math. floor (n / 10);
        }
        s = p.replace(/(零.)*零$/, '' )
             .replace(/^$/, '零' )
          + group[i] + s;
    }
    return s.replace(/(零.)*零元/, '元' )
            .replace(/(零.)+/g, '零' )
            .replace(/^$/, '零元' ) + '整' ;
};
	$('.print_amount').text( digit_uppercase('<%= @donation.amount %>') )
});
function printData(description) {
	$('.description_print').html(description)
               var data = document.getElementById('printTable').innerHTML;
     var popupWindow = window.open('','printwin',
          '');
     popupWindow.document.write('<HTML>\n<HEAD>\n');
     popupWindow.document.write('<TITLE></TITLE>\n');
     popupWindow.document.write('<URL></URL>\n');
     //popupWindow.document.write("<link href='/assets/print.css' media='print' rel='stylesheet' type='text/css' />\n");
     popupWindow.document.write('<script>\n');
     popupWindow.document.write('function print_win(){\n');
     popupWindow.document.write('\nwindow.print();\n');
     popupWindow.document.write('\nwindow.close();\n');
     popupWindow.document.write('}\n');
     popupWindow.document.write('<\/script>\n');
     popupWindow.document.write('</HEAD>\n');
     popupWindow.document.write('<BODY onload="print_win()">\n');
     popupWindow.document.write(data);
     popupWindow.document.write('</BODY>\n');
     popupWindow.document.write('</HTML>\n');
     popupWindow.document.close();
}
</script>