config/routes.rb
Rails.application.routes.draw do
  get  'users/setIdentity'

  resources :donation_lists
  resources :special_projects
  resources :downloads


	#get  'trades/donate'
	#post 'trades/post_back'
	#post 'trades/result'

  scope "(:locale)", locale: /en|zh-TW/ do
    resources :sign_reports
    resources :donations
    resources :projects
    resources :stories
    resources :links
    resources :downloaded
    as :user do
        patch '/user/confirmation' => 'users/confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "users/confirmations", :passwords => 'users/passwords' } # be careful of the order with resources users
    resources :users, only: [:index, :show, :destroy]

    post 'projects/checkLogin'
    post 'projects/delete_stage'
    post 'projects/ajax_update'

    get  'main/post_back'
    post 'main/result'
    post 'main/post_back'
    post 'main/donation'


    get  'donation', to: 'main#donation'

    get  'main/about'
    get  'main/boardMembers'
    get  'main/meetings'
    get  'main/contactUs'
    get  'main/otherLinks'
    get  'main/news'
    get  'main/donation'
    get  'main/downloaded'
    get  'main/downloadManual'
    get  'main/downloadBoardLists'
    get  'main/special'
    root 'main#about'

  end


end

app/models/project.rb
class Project < ActiveRecord::Base
   has_many :donations, :dependent => :destroy
   has_many :stages, :dependent => :destroy
   has_attached_file :pj_exp_attachment,
      :url  => "/assets/pj_exp_attachments/:id/:style/:basename.:extension"
      #:path => ":rails_root/public/assets/pj_exp_attachments/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :pj_exp_attachment
   
   has_attached_file :pj_donation_attachment,
      :url  => "/assets/pj_donation_attachments/:id/:style/:basename.:extension"
      #:path => ":rails_root/public/assets/pj_donation_attachments/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :pj_donation_attachment
   
   has_attached_file :pj_attachment,
      :url  => "/assets/pj_attachments/:id/:style/:basename.:extension"
      #:path => ":rails_root/public/assets/pj_attachments/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :pj_attachment
   
   has_attached_file :pj_cover, :styles => { :original => "1024>" },
      :url  => "/assets/pj_covers/:id/:style/:basename.:extension"
      #:path => ":rails_root/public/assets/pj_covers/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :pj_cover
   
   validates :name, :kind, :year, :donate_begin_at, :donate_end_at, :exe_desc,  presence: true
   validates :account_begin, :account_end, :account, :password, presence: true , if: "kind==1" #委辦計畫
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:checkLogin]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :get_next_stage_id, only: [:new, :edit]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where("kind = ? and id != ?", params[:pj_kind], 1).order('id DESC').paginate(per_page: 30, page: params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    set_pj_account
  end

  # GET /projects/1/edit
  def edit
    @pj_account = @project.account
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    if params[:project][:kind].to_i == GLOBAL_VAR['project_delegate'].to_i
      @project.exe_desc = 'none'
      @project.donate_begin_at = Time.zone.now
      @project.donate_end_at = Time.zone.now
      @project.account_begin = Time.zone.now 
    end
    unless params[:project][:year].blank?
      @project.year = DateTime.strptime(params[:project][:year], "%Y")
    end
    @project.save!
    #stage create
    unless params[:stage_id].blank?
      params[:stage_id].each do |key, value|
        stage = Stage.create(project_id: @project.id, title: params[:stage_title][key], stageDate: params[:stage_date][key], description: params[:stage_description][key], video_url: params[:stage_url][key])
        store_stage_image(stage, params[:stage], key)
        stage.save!
      end
    end
    #end stage create
    redirect_to @project, pj_kind: @project.kind, notice: '成功新增計畫'
    rescue ActiveRecord::RecordInvalid
    params[:pj_kind] = params[:project][:kind].to_i
    get_next_stage_id
    set_pj_account
    render "edit"
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    check_delete exp_at: params[:exp_attachment_delete], don_at: params[:donation_attachment_delete], pj_at: params[:attachment_delete], cover_at: params[:cover_delete]
    @project.update(project_params)
    unless params[:project][:year].blank?
      @project.year = DateTime.strptime(params[:project][:year], "%Y")
    end
    @project.save!
    record_log
    #stage update
    unless params[:stage_id].blank?
      params[:stage_id].each do |key, value|
        stage = @project.stages.find_by_id(key)
        #delete stage image
        unless stage.blank?
          if params[:stage_image_delete][key] == 'true'
            stage.image = nil
          end
          stage.title = params[:stage_title][key]
          stage.stageDate = params[:stage_date][key]
          stage.description = params[:stage_description][key]
          stage.video_url = params[:stage_url][key]
          store_stage_image(stage, params[:stage], key)
        else
          stage = Stage.create(project_id: @project.id, title: params[:stage_title][key], stageDate: params[:stage_date][key], description: params[:stage_description][key], video_url: params[:stage_url][key])
          store_stage_image(stage, params[:stage], key)    
        end
        stage.save!
      end
    end
    #end stage update
    redirect_to @project, pj_kind: @project.kind, notice: '成功更新計畫'
    rescue ActiveRecord::RecordInvalid
    params[:pj_kind] = params[:project][:kind].to_i
    get_next_stage_id
    @pj_account = @project.account
    render "edit"
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to({ controller: "projects", action: 'index' , pj_kind: @project.kind}, notice: '成功刪除計畫') 
  end
  
  def delete_stage
    stage = Stage.find_by_id(params[:id])
    stage.destroy
    render json: {success: true, message: '成功刪除' }.to_json
  end
  
  def checkLogin
    @project = Project.find_by_account_and_password(params[:project_account], params[:project_password])
    if @project.blank?
      render json: { success: false }.to_json
    elsif @project.account_end < Time.zone.now
      render json: { success: false }.to_json  
    else
      render json: { success: true, id: @project.id, 
                     name: @project.name, budget: @project.budget || 0, exe_desc: @project.exe_desc,
                     description: @project.description, year: @project.year.strftime("%Y"),
                     file_name: @project.pj_attachment_file_name, file_url: @project.pj_attachment.url,
                     exp_personnel: @project.exp_personnel, exp_mix: @project.exp_mix,
                     exp_business: @project.exp_business, exp_other: @project.exp_other,
                     balance: @project.balance || 0,                      
                     #income: @project.donations.where("donate_date >= ? and donate = ? ", Time.zone.now.beginning_of_year, true ).sum(:amount),
                     account_end: @project.account_end.strftime("%Y-%m-%d"),   
                     income: @project.income || 0,
                     last_year_balance: @project.last_year_balance || 0,
                     last_year_exp: @project.last_year_exp || 0,
                     exp_file_name: @project.pj_exp_attachment_file_name, exp_file_url: @project.pj_exp_attachment.url}.to_json
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:kind, :year, :name, :description, :budget, :balance, :exe_desc, :abbreviation, :account_begin, :account_end, :income, :account, :password, :pj_attachment, :pj_cover, :donate_begin_at, :donate_end_at, :pj_exp_attachment, :pj_donation_attachment, :email, :phone, :holder, :visible, :last_year_exp, :last_year_balance)
    end
    
    def record_log
      Log.create(user_id: current_user.id, project_id: @project.id )
    end
    
    def get_next_stage_id #so that we can generate a Stage id won't collide with existing Stage id
      unless Stage.maximum(:id).blank?
        @stage_next_id = Stage.maximum(:id).next
      else
        @stage_next_id = 1
      end
    end
    
    def get_next_project_id
      unless Project.maximum(:id).blank?
        @pj_next_id = Project.maximum(:id).next
      else
        @pj_next_id = 1
      end
    end
    
    def set_pj_account
      get_next_project_id
      @pj_account = DateTime.now.strftime("%Y%m%d")+"_"+@pj_next_id.to_s
    end
    
    def store_stage_image(stage, stage_params, key)
      unless stage_params.blank?
        unless stage_params[:image][key].blank?
          stage.image = stage_params[:image][key]
        end
      end
    end
    
    def check_delete(options = {})
      if options[:exp_at] == 'true' #delete project expense attachments
        @project.pj_exp_attachment = nil
      end
      if options[:don_at] == 'true' #delete project donation attachments
        @project.pj_donation_attachment = nil
      end
      if options[:pj_at] == 'true' #delete project attachments
        @project.pj_attachment = nil
      end
      if options[:cover_at] == 'true' #delete project cover photo
        @project.pj_cover = nil
      end
    end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def projectKindOptions
    [['自辦計畫', GLOBAL_VAR['project_self']], 
     ['委辦計畫', GLOBAL_VAR['project_delegate']]]
  end
end

app/views/projects/_delegate_form.html.erb
<%= form_for @project , html: { multipart: true , id: "projectForm"} do |f| %>
<div class="container" style="margin-top: 10mm">
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :kind, :value => GLOBAL_VAR['project_delegate']%>
  <%= hidden_field_tag(:attachment_delete, false) %>
  <%= hidden_field_tag(:exp_attachment_delete, false) %>
  <%= hidden_field_tag(:donation_attachment_delete, false) %>
  <%= hidden_field_tag(:cover_delete, false) %>
  <div class="form-group row">
		<div class="col-sm-offset-9 col-sm-2 pull-right-lg">
			<%= f.submit '儲存',  class: "btn btn-info save-btn"  %>
		</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">名稱*</label>
  		<div class="col-sm-6">
  			<%= f.text_field :name, class: "form-control", placeholder: "全稱" %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">簡稱</label>
  		<div class="col-sm-6">
  			<%= f.text_field :abbreviation, class: "form-control", placeholder: "簡稱" %>
    	</div>
  </div>  
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">描述</label>
  		<div class="col-sm-6">
  			<%= f.text_area :description, class: "form-control", placeholder: "描述" %>
    	</div>
  </div>
<div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">主持人</label>
  		<div class="col-sm-6">
  			<%= f.text_field :holder, class: "form-control", placeholder: "主持人" %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">聯絡人電話</label>
  		<div class="col-sm-6">
  			<%= f.phone_field :phone, class: "form-control", placeholder: "聯絡人電話" %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">Email</label>
  		<div class="col-sm-6">
  			<%= f.email_field :email, class: "form-control", placeholder: "Email" %>
    	</div>
  </div>  
  <div class="form-group row">
		<label class="col-sm-offset-2 col-sm-2 control-label">西元年度*</label>
		<div class="col-sm-6">
			<%= f.text_field :year, class: "form-control", id: 'datetimepicker_year', placeholder: "西元年度" %>	
		</div>
	    <script type="text/javascript">
	            $(function () {
	                $('#datetimepicker_year').datetimepicker({
						format : 'YYYY'		                
	                });
	            });
	    </script>	
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">去年餘額</label>
  		<div class="col-sm-6">
  			<%= f.number_field :last_year_balance, class: "form-control", placeholder: "去年餘額" %>
    	</div>
  </div>  
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">預算</label>
  		<div class="col-sm-6">
  			<%= f.number_field :budget, class: "form-control", placeholder: "預算" %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">收入</label>
  		<div class="col-sm-6">
  			<%= f.number_field :income, class: "form-control", placeholder: "收入" %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">支出</label>
  		<div class="col-sm-6">
  			<%= f.number_field :last_year_exp, class: "form-control", placeholder: "支出" %>
    	</div>
  </div>  
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">餘額</label>
  		<div class="col-sm-6">
  			<%= f.number_field :balance, class: "form-control", placeholder: "餘額" %>
    	</div>
  </div>
  <!--
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">前台顯示</label>
  		<div class="col-sm-6">
  			<%= f.radio_button :visible, "1"%>是      
  			<%= f.radio_button :visible, "0",:checked => true, :style => "margin-left:20px;"%>否
		</div>
  </div>  
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">執行狀況描述*</label>
  		<div class="col-sm-6">
  			<%= f.text_area :exe_desc, class: "form-control", placeholder: "執行狀況描述" %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">計畫封面</label>
  	<div class="col-sm-6">
  		<%= file_field_tag "project[pj_cover]", type: :file, accept: "image/*"%>
  	</div>
  </div>
  -->
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">收支明細</label>
  	<div class="col-sm-6">
  		<%= file_field_tag "project[pj_exp_attachment]", type: :file%>
  	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">捐款名冊</label>
  	<div class="col-sm-6">
  		<%= file_field_tag "project[pj_donation_attachment]", type: :file%>
  	</div>
  </div>
  <!--
  <div class="form-group row">
		<label class="col-sm-offset-2 col-sm-2 control-label">捐款開始*</label>
		<div class="col-sm-6">
			<%= f.text_field :donate_begin_at, class: "form-control", id: 'datetimepicker_donate_begin_at', placeholder: "日期"%>	
		</div>
	    <script type="text/javascript">
	            $(function () {
	                $('#datetimepicker_donate_begin_at').datetimepicker({
						format : 'YYYY/MM/DD',
						defaultDate:'1990/1/1'		                
	                });
	                
	                 $("#datetimepicker_donate_begin_at").on("dp.change", function(e) {
            			$('#datetimepicker_donate_end_at').data("DateTimePicker").minDate(e.date);
        			});
	            });
	    </script>	
  </div>
  <div class="form-group row">
		<label class="col-sm-offset-2 col-sm-2 control-label">捐款結束*</label>
		<div class="col-sm-6">
			<%= f.text_field :donate_end_at, class: "form-control", id: 'datetimepicker_donate_end_at', placeholder: "日期"%>	
		</div>
	    <script type="text/javascript">
	            $(function () {
	                $('#datetimepicker_donate_end_at').datetimepicker({
						format : 'YYYY/MM/DD',
						defaultDate:'1990/1/2'		 		                
	                });
	                $("#datetimepicker_donate_end_at").on("dp.change", function(e) {
            			$('#datetimepicker_donate_begin_at').data("DateTimePicker").maxDate(e.date);
        			});
	            });
	    </script>	
  </div>
  -->
  <% if params[:pj_kind].to_i==GLOBAL_VAR['project_delegate']%>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">計畫代號*</label>
  		<div class="col-sm-6">
  			<%= f.text_field :account, class: "form-control", placeholder: "計畫代號", :readonly => true %>
    	</div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">計畫密碼*</label>
  		<div class="col-sm-6">
  			<%= f.text_field :password, class: "form-control", placeholder: "計畫密碼" %>
    	</div>
  </div>
  <!--
  <div class="form-group row">
		<label class="col-sm-offset-2 col-sm-2 control-label">帳號開始*</label>
		<div class="col-sm-6">
			<%= f.text_field :account_begin, class: "form-control", id: 'datetimepicker_account_begin', placeholder: "日期" %>	
		</div>
	    <script type="text/javascript">
	            $(function () {
	                $('#datetimepicker_account_begin').datetimepicker({
						format : 'YYYY/MM/DD',		  
	                });
	                $("#datetimepicker_account_begin").on("dp.change", function(e) {
            			$('#datetimepicker_account_end').data("DateTimePicker").minDate(e.date);
        			});
	            });
	    </script>	
  </div>
  -->
  <div class="form-group row">
		<label class="col-sm-offset-2 col-sm-2 control-label">帳號結束*</label>
		<div class="col-sm-6">
			<%= f.text_field :account_end, class: "form-control", id: 'datetimepicker_account_end', placeholder: "日期" %>	
		</div>
	    <script type="text/javascript">
	            $(function () {
	                $('#datetimepicker_account_end').datetimepicker({
						format : 'YYYY/MM/DD'		                
	                });
	                $("#datetimepicker_account_end").on("dp.change", function(e) {
            			$('#datetimepicker_account_begin').data("DateTimePicker").maxDate(e.date);
        			});
	            });
	    </script>	
  </div>
  <% end %>
</div>
<% end %>
<%=render "projects/script" %>   
<script>
$(document).on('ready', function() {
	$('#project_kind').val('<%= GLOBAL_VAR['project_delegate']%>');
	$('#project_account').val('<%= @pj_account %>')
});
</script>

app/views/projects/_sub_donation_table.html.erb
<%= link_to donation_path(donation) do %>
	<div class="col-md-4">
	  <table class="table backend_index_table">
	  	<tbody>
	      <tr>
	        <th>抬頭: </th>
	        <td><%= donation.receipt_title %></td>
	      </tr>
	      <tr>
	        <th>金額: </th>
	        <td><%= number_with_delimiter donation.amount || 0%>元</td>
	      </tr>
	      <tr>
	        <th>捐款方式: </th>
	        <td><%= Hash[donateWayOptions].rassoc(donation.donate_way).first %></td>
	      </tr>
	      <tr>
	      	<% if donation.donate %>
	      		<th>已捐款</th>
	      	<% else %>
	      		<th>尚未捐款</th>
	      	<% end %>
	      </tr>
	      <tr>
	    </tbody>
	  </table>
	</div>
<% end %>

app/views/projects/_sub_project_table.html.erb
<%= link_to project_path(project, :pj_kind => project.kind) do %>
	<div class="col-md-4">
		<table class="table backend_index_table">
			<tbody>
		      <tr>
		        <td><%= project.name %></td>
		      </tr>
		      <%if project.kind.to_i == GLOBAL_VAR['project_self'].to_i %>
		      <tr>
		        <td style="text-align:center;">
		        	<% if project.pj_cover.exists? %>
				 		<%= image_tag project.pj_cover.url, class: "backend_index_table_image"%>
				 	<% else %>
				 		<%= image_tag "/assets/noPhoto-icon.png" , class: "backend_index_table_image"%>
				 	<% end %>
		        </td>
		      </tr>
		      <%end%>
	    	</tbody>
	  	</table>
	</div>
<% end %>

app/views/projects/edit.html.erb
<%if params[:pj_kind].to_i==GLOBAL_VAR['project_self']%>
<%= render 'self_form' %>
<%end%>
<%if params[:pj_kind].to_i==GLOBAL_VAR['project_delegate']%>
<%= render 'delegate_form' %>
<%end%>

app/views/projects/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3 style="letter-spacing: 2px;"><%= Hash[projectKindOptions].rassoc(params[:pj_kind].to_i).first%></h3>
			<%= link_to "新增",{controller: 'projects', action: 'new', pj_kind: params[:pj_kind]}, data: {no_turbolink: true}, class: 'add-btn pull-right' %>		
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
	    <% @projects.each do |project| %>
	    	<%= render "sub_project_table", project: project %>
	    <% end %>
    </div>
</div>
  

app/views/projects/new.html.erb
<%if params[:pj_kind].to_i==GLOBAL_VAR['project_self']%>
<%= render 'self_form' %>
<%end%>
<%if params[:pj_kind].to_i==GLOBAL_VAR['project_delegate']%>
<%= render 'delegate_form' %>
<%end%>

app/views/projects/show.html.erb
  <div class="row" style="margin-bottom: 20px;">
  	<h3 class="col-md-offset-1 col-sm-5"><%= @project.name %>計畫</h3>
  </div>
<div class="container-fluid">
	<div class="row">	
		<div class="col-md-offset-9 pull-right-lg">
			<%= link_to "編輯", edit_project_path(@project, :pj_kind => @project.kind), data: { no_turbolink: true }, class: 'btn btn-default edit-btn' %>
			<%= link_to '刪除', @project, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger delete-btn'%>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">簡稱</div>
	    <div class="col-md-4 show-content" style="font-size: 24px;"> <%= @project.abbreviation %></div>
	</div>
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">描述</div>
	    <div class="col-md-5 show-content">&nbsp&nbsp<%= @project.description %></div>
	</div>
	<div class="row">
	    <div class="col-md-3 col-md-offset-3 show-title">西元年度</div>
	  	<div class="col-md-3 show-content" style="font-size: 24px;"> <%= @project.year.strftime("%Y") %></div>
	</div>
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">去年餘額</div>
	    <div class="col-md-3 show-content" style="font-size: 24px;"> <%= number_with_delimiter @project.last_year_balance || 0%> 元</div>
	</div>	
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">預算</div>
		<div class="col-md-3 show-content" style="font-size: 24px;"> <%=  number_with_delimiter @project.budget || 0%> 元</div>
	</div>
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">收入</div>
	    <div class="col-md-3 show-content" style="font-size: 24px;"> <%=  number_with_delimiter @project.income || 0%> 元</div>
	</div>
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">支出</div>
	    <div class="col-md-3 show-content" style="font-size: 24px;"> <%=  number_with_delimiter @project.last_year_exp || 0%> 元</div>
	</div>	
	<div class="row">
	    <div class="col-md-3 col-md-offset-3 show-title">餘額</div>
	    <div class="col-md-3 show-content" style="font-size: 24px;"> <%=  number_with_delimiter @project.balance || 0%> 元</div>
	</div>
	<div class="row" >
	  <div class="col-md-3 col-md-offset-3 show-title">收支明細</div>
	  <div class="col-md-3 show-content"> <% unless @project.pj_exp_attachment_file_name.blank? %><%= link_to @project.pj_exp_attachment_file_name, @project.pj_exp_attachment.url(:original, false) %><% end %></div>
	</div>
	<% if @project.kind == GLOBAL_VAR['project_self']%>
	<div class="row">
		<div class="col-md-3 col-md-offset-3 show-title">顯示前台</div>
	    <div class="col-md-3 show-content" style="font-size: 24px;"> <% if @project.visible%>是 <% else %>否<% end %></div>
	</div>	
	<div class="row">
	  <div class="col-md-3 col-md-offset-3 show-title">執行狀況描述</div>
	  <div class="col-md-3 show-content" style="font-size: 24px;"> <%= @project.exe_desc  %></div>
	</div>	
	<% elsif @project.kind == GLOBAL_VAR['project_delegate']%>
	<!--
	<div class="row">
	  <div class="col-md-3 col-md-offset-3 show-title">帳號開始時間</div>
	  <div class="col-md-3 show-content" style="font-size: 24px;"> <%= @project.account_begin.strftime("%Y-%m-%d") %></div>
	</div>
	-->
	<div class="row">
	  <div class="col-md-3 col-md-offset-3 show-title">帳號結束時間</div>
	  <div class="col-md-3 show-content" style="font-size: 24px;"> <%= @project.account_end.strftime("%Y-%m-%d") %></div>
	</div>
	<div class="row">
	  <div class="col-md-3 col-md-offset-3 show-title">捐款</div>
	</div>
	<% end %>
	<div class="row">		
		<div class="col-md-offset-1 col-md-10" style="margin-top: 40px;">
			<div style="border-top: 1px solid #fff;"></div>
		</div>					
	</div>
	<div class="row" style="margin: 20px 0px;">
  		<h3 class="col-md-offset-1 col-sm-5 top-title">捐款<span class="top-title-span">明細</span></h3>
  	</div>
	<div class="container">
		<% @project.donations.each do |donation| %>
			<%= render "sub_donation_table", donation: donation %>
		<% end %>
	</div>
</div>