config/routes.rb
Rails.application.routes.draw do
  get  'users/setIdentity'

  resources :donation_lists
  resources :special_projects
  resources :downloads


	#get  'trades/donate'
	#post 'trades/post_back'
	#post 'trades/result'

  scope "(:locale)", locale: /en|zh-TW/ do
    resources :sign_reports
    resources :donations
    resources :projects
    resources :stories
    resources :links
    resources :downloaded
    as :user do
        patch '/user/confirmation' => 'users/confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "users/confirmations", :passwords => 'users/passwords' } # be careful of the order with resources users
    resources :users, only: [:index, :show, :destroy]

    post 'projects/checkLogin'
    post 'projects/delete_stage'
    post 'projects/ajax_update'

    get  'main/post_back'
    post 'main/result'
    post 'main/post_back'
    post 'main/donation'


    get  'donation', to: 'main#donation'

    get  'main/about'
    get  'main/boardMembers'
    get  'main/meetings'
    get  'main/contactUs'
    get  'main/otherLinks'
    get  'main/news'
    get  'main/donation'
    get  'main/downloaded'
    get  'main/downloadManual'
    get  'main/downloadBoardLists'
    get  'main/special'
    root 'main#about'

  end


end

app/models/story.rb
class ActiveRecord::Base
  def self.has_translation(*attributes)    
    attributes.each do |attribute|
      define_method "#{attribute}" do
        if I18n.locale == I18n.default_locale
          self.read_attribute(attribute)
        else
          self.send "#{attribute}_#{I18n.locale}"
        end
      end
    end
  end
end

class Story < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
  validates :topic, :description, :news_date, presence: true
  has_translation :topic, :description
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.save!
    if params[:images]
        params[:images].each { |image|
          @story.pictures.create(image: image)
       }
    end
    redirect_to @story, notice: '成功新增最新消息' 
    rescue ActiveRecord::RecordInvalid
    render :action=>:edit
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    if params[:images_delete] == 'true'
      @story.pictures.destroy_all
    end
    
    if params[:images]
        params[:images].each { |image|
          @story.pictures.create(image: image)
       }
    end
    if @story.update(story_params)
      redirect_to @story, notice: '成功更新最新消息' 
    else
      render :action => :edit
    end
    
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:description, :description_en, :topic, :topic_en, :video_url, :news_date)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for @story, :html => {class: "form-horizontal", role: "form", :multipart => true } do |f| %>
<div class="container" style="margin-top: 10mm">  
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag(:images_delete, false) %>
  <div class="form-group">
    <label class="col-sm-offset-2 col-sm-2 control-label">標題*</label>
    <div class="col-sm-4"><%= f.text_field :topic, class: "form-control", placeholder: '標題' %></div>
  </div>
  <div class="form-group">
    <label class="col-sm-offset-2 col-sm-2 control-label">英文標題</label>
    <div class="col-sm-4"><%= f.text_field :topic_en, class: "form-control", placeholder: '英文標題' %></div>
  </div>
  <div class="form-group">
    <label class="col-sm-offset-2 col-sm-2 control-label">描述*</label>
    <div class="col-sm-4"><%= f.text_area :description , class: "form-control", placeholder: '描述'%></div>
  </div>
  <div class="form-group">
    <label class="col-sm-offset-2 col-sm-2 control-label">英文描述</label>
    <div class="col-sm-4"><%= f.text_area :description_en , class: "form-control", placeholder: '英文描述'%></div>
  </div>
  <div class="form-group row">
		<label class="col-sm-offset-2 col-sm-2 control-label">時間*</label>
		<div class="col-sm-4">
			<%= f.text_field :news_date, class: "form-control", id: 'datetimepicker_news_date', placeholder: "日期" %>	
		</div>
	    <script type="text/javascript">
	            $(function () {
	                $('#datetimepicker_news_date').datetimepicker({
						format : 'YYYY/MM/DD'		                
	                });
	            });
	    </script>	
  </div>
  <div class="form-group">
    <label class="col-sm-offset-2 col-sm-2 control-label">Youtube嵌入碼</label>
    <div class="col-sm-4"><%= f.text_field :video_url, class: "form-control", placeholder: '嵌入碼' %></div>
  </div>
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label"></label>
  	<div class="col-sm-6"><%=image_tag 'embedded.jpg', style: "width: 100%;" %></div>
  </div>
  
  <div class="form-group row">
  	<label class="col-sm-offset-2 col-sm-2 control-label">圖片</label>
  	<div class="col-sm-4"><%= file_field_tag "images[]", type: :file, accept: "image/*", multiple: true%></div>
  </div>
  <div class="form-group row">
		<div class="col-sm-offset-9 col-sm-2">
			<%= f.submit '儲存',  class: "btn btn-info save-btn"  %>
		</div>
  </div>
</div>
<% end %>
<script>
$(document).on('ready', function() {
     $("#images_").fileinput({
     	initialPreview: [
     		<% @story.pictures.each  do |p| %> 
		    <% if !p.blank? %>
        		'<%= image_tag p.image.url, class: 'file-preview-image' %>',
			<% end %>
			<% end %>		
		             ],
		showUpload: false,
        previewFileType: "image",
        browseClass: "btn btn-success",
        browseLabel: "Pick Image",
        browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
        removeClass: "btn btn-danger",
        removeLabel: "Delete",
        removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
        uploadClass: "btn btn-info",
        uploadLabel: "Upload",
        uploadIcon: "<i class=\"glyphicon glyphicon-upload\"></i> "
    });
    
     $('#images_').on('fileloaded', function(event, file, previewId, index, reader) {
        $('#images_delete').val(true);
    });
    $('#images_').on('fileclear', function(event) {
    	$('#images_delete').val(true);
    });
});
</script>

app/views/stories/_sub_story_table.html.erb
<% if index%3 == 0%>
	<div class="row">
<% end %>

<%= link_to story_path(story) do%>
<div class="col-md-4">
	<table class="table story-table backend_index_table">
		<tbody>
	      <tr style="height: 70px;">
	        <td colspan="2"><%= story.topic %></td>
	      </tr>
	      <tr style="height: 320px;">
	        <td  colspan="2" style="font-size: 16px;">
	        	<% if story.description.length > 239 %>
				  	<%= truncate(story.description.gsub("\r\n", "\n"), length: 150) %>
				    <%= link_to '  Read more', '', class: "read-more-#{story.id}" %>
				 <% else %>
				    <%= story.description.gsub("\r\n", "\n") %>
				 <% end %>
	        </td>
	      </tr>
    	</tbody>
  	</table>
</div>
<% end %>

<% if index%3 == 2%>
	</div>
<% end %>

app/views/stories/edit.html.erb
<%= render 'form' %>

app/views/stories/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">	
			<h3 style="letter-spacing: 2px;">消息</h3>
			<%= link_to "新增", new_story_path, data: { no_turbolink: true }, class: 'add-btn pull-right' %>				
		</div>		
	</div>
</div>
<div class="container">
		<% @stories.order('news_date desc').each_with_index do |story, index| %>
    		<%= render "sub_story_table", story: story , index: index%>
		<% end %>
</div>

<script>
	<% @stories.each do |story| %>
	  $('.read-more-<%= story.id %>').on('click', function(e) {
	    e.preventDefault()
	    $(this).parent().html('<%= story.description.gsub("\r\n", "\\n") %>')
	  })
	<% end %>
</script>

app/views/stories/new.html.erb
<%= render 'form' %>

app/views/stories/show.html.erb
<div class="container" style="margin-bottom: 20px;">
  <div class="row">
	<h3 class="col-md-offset-2 col-md-8">消息</h3>
  </div>
</div>
<div class="container">
	<div class="row">	
		<div class="col-md-10">
			<%= link_to '刪除', @story, method: :delete, data: { confirm: '確定要刪除嗎?' } , class: 'delete-btn pull-right'%>			
			<%= link_to '編輯', edit_story_path(@story) , data: { no_turbolink: true }, class: 'edit-btn pull-right', style: 'margin-right: 20px;'%> 
		</div>
	</div>
</div>
<div class="container" style="margin-top: 23px;">
	<% unless @story.pictures.blank? %>
	<div class="row">
		<div class="col-md-offset-2 col-md-8">
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <% @story.pictures.each_with_index do |p, i|%> 
					<%if i==0 %>
						<li data-target="#carousel-example-generic" data-slide-to="<%=i%>" class="active"></li>
					<% else %>
					    <li data-target="#carousel-example-generic" data-slide-to="<%=i%>"></li>    
					<% end %>
				<% end %> 
			  </ol>
			
			  <!-- Wrapper for slides -->
			  <div class="story_carousel-inner carousel-inner" role="listbox">
			  	<% @story.pictures.each_with_index do |p, i| %>
				  	<% if i==0 %>
					    <div class="item active">
					      <div class="story_carousel_img" style="background-image: url('<%=p.image.url%>')"></div>
					    </div>
				    <% else %>
						<div class="item">
					      <div class="story_carousel_img" style="background-image: url('<%=p.image.url%>')"></div>
					    </div>	    
				    <% end %>
			    <% end %>
			  </div>
			
			  <!-- Left and right controls -->
			  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="border-radius: 23px;">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="border-radius: 23px;">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
	</div>
	<% end %>
	<div class="row" style="margin-top: 23px;">
	  	<div class="col-md-offset-2 col-md-2 show-title">標題</div>
	  	<div class="col-md-4 show-content"> <%= @story.topic %></div>
	</div>
	<div class="row">
	  	<div class="col-md-offset-2 col-md-2 show-title">英文標題</div>
	  	<div class="col-md-4 show-content"> <%= @story.topic_en %></div>
	</div>
	<div class="row">
	  	<div class="col-md-offset-2 col-md-2 show-title">描述</div>
	  	<div class="col-md-4 show-content"> <%= @story.description %></div>
	</div>
	<div class="row">
	  	<div class="col-md-offset-2 col-md-2 show-title">英文描述</div>
	  	<div class="col-md-4 show-content"> <%= @story.description_en %></div>
	</div>
	<div class="row">
	  <div class="col-md-2 col-md-offset-2 show-title">Youtube嵌入碼</div>
	  <div class="col-md-5" style="padding: 23px;"><%= show_video(data: @story.video_url) %> </div>
	</div>
</div>